spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${db.postgres-addr}
    username: ${db.postgres-username}
    password: ${db.postgres-password}
    database-platform: org.hibernate.dialect.PostgreSQLDialect